### ISSUE TITLE
Not responsive on specific browser viewport size and flex it's supported

### ISSUE THREAD

**Issue by smoglica** [CodyHouse/cd-masonry-changelog#1]
I tested only with chrome and I notice this error when resizing the window `<= 334px`

![Screenshot from 2020-02-14 09-35-43](https://user-images.githubusercontent.com/17332096/74515020-0594dd80-4f0e-11ea-95a8-dafc63b9fbf7.png)

The same error appears when loading the page with a viewport size `<= 319px`

![Screenshot from 2020-02-14 09-42-58](https://user-images.githubusercontent.com/17332096/74515341-abe0e300-4f0e-11ea-8b40-03435a2854c7.png)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We just pushed a modified version that should fix the bug. 
Please let me know if you are still experiencing this issue. Cheers!
