### ISSUE TITLE
Masonry js error

### ISSUE THREAD

**Issue by iamrobert** [CodyHouse/cd-masonry-changelog#2]
For me, masonry seems to create a js error on load or resize if you have less than 8 items:
 
```
Uncaught TypeError: Cannot read property 'style' of undefined
    at layItems (_1_masonry.js:103)
    at HTMLDivElement.<anonymous> (_1_masonry.js:56)
    at _1_masonry.js:168
    at doneResizing (_1_masonry.js:168)
```

It sees to be related to this line:
 `lastItemCol.style.flexBasis = masonryHeight - grid.colHeights[i] + lastItemCol.getBoundingClientRect().height - 5 + 'px';`

If I wrap it in:

```
// grid.items
if (grid.items.length >= 8 ) {
     lastItemCol.style.flexBasis = masonryHeight - grid.colHeights[i] + lastItemCol.getBoundingClientRect().height - 5 + 'px';
             }
```

It seems to be disappear.
![problem](https://i.imgur.com/hYjN4MF.jpg)

I am using the default scss.

**Comment by claudia-romano** [comment]
Hi there,
I was not able to recreate the issue with a gallery of less than 8 elements. 

Are you using custom JS that may be affecting the component? Could you recreate the bug using your gallery elements but removing any custom JS? Thanks.

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
