### ISSUE TITLE
Images outside container

### ISSUE THREAD

**Issue by jmsobe** [CodyHouse/cd-masonry-changelog#3]
When incorporating the masonry component inside the Side Navigation V3 component the image items do not adhere to the container size on initial load. If I resize the window the items will reflow. 

![CleanShot 2021-12-20 at 09 53 03@2x](https://user-images.githubusercontent.com/3740448/146811735-629dd200-1ee0-4664-8ae1-e6bfea225e76.png)

**Comment by claudia-romano** [comment]
Hi there, could you please try importing the js code of the responsive sidebar and the expandable side navigation before the masonry one? For example, if you are using our Gulp file to automatically create your final js file, you can rename the masonry js file to _2_masonry.js to make sure it is loaded last:

<img width="356" alt="Screenshot 2021-12-21 at 14 57 07" src="https://user-images.githubusercontent.com/5512545/146941811-17d765f2-19c2-408d-8233-7c2cf80803f9.png">

This should fix your issue. Thanks!

**Comment by jmsobe** [comment]
Thanks for responding, this is my new ordering of files, doesn't seem to
make any difference unfortunately

[image: CleanShot 2021-12-21 at ***@***.***

**Comment by jmsobe** [comment]
sorry wrong image

[image: CleanShot 2021-12-21 at ***@***.***

**Comment by jmsobe** [comment]
Yes, that fixed it, thank you.
